stages:
    - test
    - deploy

test:
    image: node:10
    stage: test
    script:
        - npm install
        - npm run test-coverage
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

deploy:
    stage: deploy
    image: max107/alpine-fabric3
    dependencies:
        - test
    script:
        - fab production deploy
    environment:
        name: production
        url: https://api.reogen.ru/
    only:
        - master
