---
- hosts: staging
  vars:
    project_path: "/home/{{ ansible_user }}/server"
    git_repository: "git@github.com:dreamteam-tech/bloom-server.git"
    git_branch: 'develop'
    app_vars:
      NODE_ENV: "production"
      APP_RELEASE: "{{ lookup('env', 'STAGING_APP_RELEASE') }}"
      JWT_SECRET: "{{ lookup('env', 'STAGING_JWT_SECRET') }}"
      SENTRY_DSN: "{{ lookup('env', 'STAGING_SENTRY_DSN') }}"
      RDS_USERNAME: "{{ lookup('env', 'STAGING_RDS_USERNAME') }}"
      RDS_PASSWORD: "{{ lookup('env', 'STAGING_RDS_PASSWORD') }}"
      RDS_DB_NAME: "{{ lookup('env', 'STAGING_RDS_DB_NAME') }}"
      RDS_HOSTNAME: "{{ lookup('env', 'STAGING_RDS_HOSTNAME') }}"
      RDS_PORT: "{{ lookup('env', 'STAGING_RDS_PORT') }}"
  tasks:
    - include_tasks: tasks/deploy.yaml
